version: '3.8'

services:
  # Go API Service
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=devsmailgo
      - DB_PASSWORD=devsmailgo_password
      - DB_NAME=devsmailgo
      - LDAP_HOST=openldap
      - LDAP_PORT=389
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_BIND_DN=cn=admin,dc=example,dc=com
      - LDAP_BIND_PASSWORD=admin_password
    depends_on:
      - mysql
      - openldap
    volumes:
      - ./logs:/app/logs
    networks:
      - mail_network

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devsmailgo
      MYSQL_USER: devsmailgo
      MYSQL_PASSWORD: devsmailgo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mail_network

  # OpenLDAP Server
  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "Example Inc"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_CONFIG_PASSWORD: "config_password"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap/init:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - mail_network

  # phpLDAPadmin (LDAP Web Interface)
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - openldap
    networks:
      - mail_network

  # Postfix Mail Server
  postfix:
    image: catatnight/postfix
    hostname: mail.example.com
    environment:
      maildomain: example.com
      smtp_user: devsmailgo:devsmailgo_password
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - postfix_data:/var/mail
      - ./postfix/config:/etc/postfix
    networks:
      - mail_network

  # Dovecot IMAP Server
  dovecot:
    image: dovemark/dovecot:latest
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - dovecot_data:/var/mail
      - ./dovecot/config:/etc/dovecot
    depends_on:
      - postfix
    networks:
      - mail_network

  # Roundcube Webmail
  roundcube:
    image: roundcube/roundcubemail:latest
    environment:
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: mysql
      ROUNDCUBEMAIL_DB_NAME: roundcube
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: roundcube_password
      ROUNDCUBEMAIL_SMTP_SERVER: postfix
      ROUNDCUBEMAIL_IMAP_SERVER: dovecot
    ports:
      - "8082:80"
    depends_on:
      - mysql
      - postfix
      - dovecot
    volumes:
      - roundcube_data:/var/www/html/config
    networks:
      - mail_network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mail_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - roundcube
    networks:
      - mail_network

volumes:
  mysql_data:
  ldap_data:
  ldap_config:
  postfix_data:
  dovecot_data:
  roundcube_data:
  redis_data:

networks:
  mail_network:
    driver: bridge 